
package sample.user.crud.basic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.soap.SOAPException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "crudPort", targetNamespace = "http://basic.crud.user.sample")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CrudPort {


    /**
     * 
     * @param request
     * @return
     *     returns sample.user.crud.basic.ReadResponse
     */
    @WebMethod
    @WebResult(name = "response", partName = "response")
    public ReadResponse read(
        @WebParam(name = "request", partName = "request")
        ReadRequest request) throws SOAPException;

    /**
     * 
     * @param request
     * @return
     *     returns sample.user.crud.basic.CreateResponse
     */
    @WebMethod(action = "http://basic.crud.user.sample")
    @WebResult(name = "response", partName = "response")
    public CreateResponse create(
        @WebParam(name = "request", partName = "request")
        CreateRequest request) throws SOAPException;

    /**
     * 
     * @param request
     * @return
     *     returns sample.user.crud.basic.UpdateResponse
     */
    @WebMethod(action = "http://basic.crud.user.sample")
    @WebResult(name = "response", partName = "response")
    public UpdateResponse update(
        @WebParam(name = "request", partName = "request")
        UpdateRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns sample.user.crud.basic.DeleteResponse
     */
    @WebMethod
    @WebResult(name = "response", partName = "response")
    public DeleteResponse delete(
        @WebParam(name = "request", partName = "request")
        DeleteRequest request);

}
